import matplotlib.pyplot as plt
import numpy as a
f=float(input("enter the frequency"))
fs=float(input("enter the sampling frequency"))
x=a.arange(0,50,0.5)
y=a.sin(2*a.pi*f*x/fs)
plt.subplot(1,5,1)
plt.plot(x,y)
plt.title('sinwave')
plt.xlabel('time')
plt.ylabel('amplitude')
b=a.cos(2*a.pi*f*x/fs)
plt.subplot(1,5,2)
plt.plot(x,b)
plt.title('coswave')
plt.xlabel('time')
plt.ylabel('amplitude')
c=y+b
plt.subplot(1,5,3)
plt.plot(x,c)
plt.title('addition of cos and sin wave')
plt.xlabel('time')
plt.ylabel('amplitude')
d=y-b
plt.subplot(1,5,4)
plt.plot(x,d)
plt.title('substraction of cosm and sin signal')
plt.xlabel('time')
plt.ylabel('amplitude')
e=y*b
plt.subplot( 1,5,5)
plt.plot(x,e)
plt.title('multiplication of signals')
plt.xlabel('time')
plt.ylabel('amplitude')
plt.show()
